#============================================
#======docker container
#============================================

spring:
  profiles: container
  application:
    name: Kafka2MongoBridge

#====mongodb====
  data:
    mongodb:
      host: ${DATABASE_HOST}
      port: ${DATABASE_PORT}
      database: ${DATABASE_NAME}

#====Kafka=====
  kafka:
    consumer:
      auto-offset-reset: earliest

management:
  port: 9002

#define in which topics the raw data should be read for each iot device
kafka:
  topic:
    smartCouch:
      raw-topic: smart-couch-raw
      groupId:  smart-couch-raw
    smartWatch:
      raw-topic: smart-watch-raw
      groupId:  smart-watch-raw
    carFuel:
      raw-topic: car-fuel-raw
      groupId:  car-fuel-raw
    refrigerator:
      raw-topic: refrigerator-raw
      groupId:  refrigerator-raw
